version: '2.3'

services:
  elastic:
    image: elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
      - logger.level=error
      #lock memory
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      interval: 5s
      retries: 500
      test: curl -s 127.0.0.1:9200 &>/dev/null

  kosh:
    image: cceh/kosh:track_meml
    ports:
      - 5000:5000
    healthcheck:
      interval: 5s
      retries: 500
      test: wget -q --spider 127.0.0.1:5000 2>&1 | grep -q HTTP
    depends_on:
      elastic:
        condition: service_healthy